### ISSUE TITLE
Provide Fedora 31 package

### ISSUE THREAD

**Issue by mweirauch** [bebosudo/olive-editor-rpm#1]
Hi! Would it be possible to provide a Fedora 31 package?

PS: Thanks for providing this copr anyway!

**Comment by bebosudo** [comment]
Done! See the installation instructions here: https://copr.fedorainfracloud.org/coprs/bebosudo/olive-editor/
Let me know if you notice any problem with the package (I'm not on f31 yet), and feel free to open a new issue.

I'm still packaging v. 0.1.2 because it's the latest stable release, but there have been several "continuous" releases of olive, which are not considered stable. The main dev also disabled the github issue tracker of the olive repo while they are restructuring the whole codebase, but you can already try out some of the new features using the latest AppImage or compiling it from source, see: https://github.com/olive-editor/olive/releases
I'll make sure to package the newest stable as soon as it's released.

**Comment by mweirauch** [comment]
Thanks for the quick reaction. I still had the f30 version installed after the upgrade, but the f31 package works fine!

The "continuous" version is kinda too experimental currently, but I guess I'll test it out once in a while. I am watching the builds and have a look at the commits. A pitty he closed the issue tracker. Already found a small bug ;)

Thanks again!

**Comment by bebosudo** [comment]
Personally I don't like these one-man-band projects, as they usually die with no-one able to take care of it; let's hope olive is able to build a community of developers.
